Resolve #99
WorksApplications/SudachiPy pull request #111
Opened 2019-12-11 15:24 UTC by izziiyt

- resolve #99
- apply flake8

Same problem reproduced
https://sudachi-dev.slack.com/archives/CBCF278AC/p1575185307012400

Stackoverflow
https://stackoverflow.com/questions/28203670/how-to-use-cython-typed-memoryviews-to-accept-strings-from-python

Modification in dartsclone
https://github.com/rixwew/darts-clone-python/pull/4

==============

I wonder why format.sh didn't reject @sorami's code change...

2019-12-12 04:19 UTC, sorami commented
@izziiyt Hi!

Just one comment, should it be `dartsclone>=0.7.0` instead of `dartsclone~=0.7.0`, as the later version (e.g., `0.8`) may have breaking changes?

2019-12-12 04:20 UTC, sorami commented
@izziiyt I am sorry, I wasn't aware of the `./scripts/format.sh`; My bad, will do next time.

Is the formatting part of the CI?

2019-12-12 05:00 UTC, izziiyt commented
@sorami 

>Just one comment, should it be dartsclone>=0.7.0 instead of dartsclone~=0.7.0, as the later version (e.g., 0.8) may have breaking changes?

It's because of the versioning rule of `dartsclone`. `dartsclone` bump minor version even if just a bug fix.   Best way is offering semantic versioning schema to @rixwew  and keep `~=`...
Please give me time, I'll talk with @rixwew.

>Is the formatting part of the CI?

I remembered .that travis rejected if format.sh fails before ... but we may have to fix .travis.yml

2019-12-13 05:18 UTC, izziiyt commented
I discussed with @rixwew https://github.com/rixwew/darts-clone-python/issues/5
@sorami You can merge this MR.

2019-12-13 05:51 UTC, sorami requested changes

2019-12-13 05:51 UTC, sorami commented on setup.py
> +            'dartsclone>=0.7.0',
This part should be `~=` too?

2019-12-13 05:52 UTC, sorami commented
Thank you for the discussion at the dartsclone issue!

2019-12-13 08:29 UTC, sorami commented
LGTM, thanks!

2019-12-13 08:30 UTC, sorami approved these changes

2019-12-13 08:30 UTC, merged